<?php
// $Id$

/**
 * @file
 * Dummy Google Analytics API server used with SimpleTest
 *
 * The server responds positively to all authentication requests, and has
 * a set of expected data requests that it will respond to.
 */

/**
 * Implement hook_menu().
 */
function google_analytics_api_test_menu() {
  $items['analytics-test/accounts/AuthSubRequest'] = array(
    'title' => 'Google Account AuthSub authentication request',
    'page callback' => 'google_analytics_api_test_accounts_authsub_request',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['analytics-test/accounts/AuthSubSessionToken'] = array(
    'title' => 'Google Account AuthSub session token retrieval',
    'page callback' => 'google_analytics_api_test_accounts_authsub_session_token',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['analytics-test/accounts/AuthSubRevokeToken'] = array(
    'title' => 'Revoke Google Account AuthSub session token',
    'page callback' => 'google_analytics_api_test_accounts_authsub_revoke_token',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['analytics-test/analytics/feeds/accounts/default'] = array(
    'title' => 'Google Analytics API account listing',
    'page callback' => 'google_analytics_api_test_analytics_feeds_accounts_default',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['analytics-test/analytics/feeds/data'] = array(
    'title' => 'Google Analytics API data retrieval',
    'page callback' => 'google_analytics_api_test_analytics_feeds_data',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/*
 * Hook to replace a Google URL for testing purposes.
 */
function google_analytics_api_test_replace_url($url) {
  /* URLs used:
   * https://www.google.com/accounts/ClientLogin
   * https://www.google.com/accounts/AuthSubRequest
   * https://www.google.com/accounts/AuthSubSessionToken
   * https://www.google.com/accounts/AuthSubRevokeToken
   * https://www.google.com/accounts/AuthSubTokenInfo
   * https://www.google.com/analytics/feeds/accounts/default
   * https://www.google.com/analytics/feeds/data
   * https://www.google.com/analytics/feeds/
   */
  return preg_replace('|^https://www.google.com/|', url('analytics-test/', array('absolute' => TRUE)), $url);
}

/**
 * Menu callback; Google Account AuthSub authentication request.
 */
function google_analytics_api_test_accounts_authsub_request() {
  // Check for scope and next parameters.
  if (!isset($_GET['scope'])) {
    die('No scope parameter sent in AuthSub request.');
  }
  if ($_GET['scope'] != 'https://www.google.com/analytics/feeds/') {
    die('Invalid scope parameter sent in AuthSub request.  Can only be "https://www.google.com/analytics/feeds/".');
  }
  if (!isset($_GET['next'])) {
    die('No next parameter sent in AuthSub request.');
  }

  // Respond to request with a redirection.
  $response = array('token' => '66cba0a214231d3fd3e7f984c7674ad0');
  drupal_set_header('Content-Type', 'text/plain');
  header('Location: ' . url($_GET['next'], array(
    'query' => http_build_query($response, '', '&'),
    'external' => TRUE)));
  die();
}

/**
 * Menu callback; Google Account AuthSub session token retrieval.
 */
function google_analytics_api_test_accounts_authsub_session_token() {
  $sent_headers = getallheaders();

  // Check for token header.
  if (!isset($sent_headers['Authorization'])) {
    exit('No authorization header sent in AuthSub request.');
  }
  $auth_token = str_replace('AuthSub token=', '', $sent_headers['Authorization']);

  // Check for correct token.
  if ($auth_token != '66cba0a214231d3fd3e7f984c7674ad0') {
    exit('Invalid token sent in AuthSub request.');
  }

  // Send back session token.
  exit('Token=5a5b356a3a02fb64019b0967e4e267b6');
}

/**
 * Menu callback; Revoke Google Account AuthSub session token.
 */
function google_analytics_api_test_accounts_authsub_revoke_token() {
  $sent_headers = getallheaders();

  // Check for token header.
  if (!isset($sent_headers['Authorization'])) {
    exit('No authorization header sent in AuthSub request.');
  }
  $auth_token = str_replace('AuthSub token=', '', $sent_headers['Authorization']);

  // Check for correct token.
  if ($auth_token != '5a5b356a3a02fb64019b0967e4e267b6') {
    exit('Invalid token sent in AuthSub request.');
  }

  // Send back session token.
  // TODO: Check the return value here to match that of Google.
  exit('token=revoked');
}

/**
 * Menu callback; Google Analytics API account listing.
 */
function google_analytics_api_test_analytics_feeds_accounts_default() {
  exit(file_get_contents(dirname(__FILE__) . '/account_listing.xml'));
}

/**
 * Menu callback; Google Analytics API data retrieval.
 */
function google_analytics_api_test_analytics_feeds_data() {
  $test_cases = array(
    'case-1' => array(
      array(
        'start-date' => '2008-10-01',
        'end-date' => '2008-10-31',
        'dimensions' => 'ga:source,ga:medium',
        'metrics' => 'ga:visits,ga:bounces',
        'sort' => '-ga:visits',
        'filters' => 'ga:medium==referral',
        'start-index' => '1',
        'max-results' => '5',
        'ids' => 'ga:10000000',
      ),
      file_get_contents(dirname(__FILE__) . '/data_feed1.xml'),
    ),
  );

  // Look for a matching test case.
  $match_case = false;
  foreach ($test_cases as $name => $test_case) {
    $match_case = $name;
    list ($parameters, $output) = $test_case;
    foreach ($parameters as $key => $value) {
      // Does the parameter in this test case match?
      if (!isset($_GET[$key]) || $_GET[$key] != $value) {
        // No.  Try the next test case.
        $match_case = false;
        break;
      }
    }
    // Did all of the parameters match?
    if ($match_case) {
      exit($output);
    }
  }
}
