# Schema for the configuration files of the google_analytics_reports module.

google_analytics_reports.settings:
  type: config_object
  label: 'Google Analytics Reports settings'
  mapping:
    metadata_etag:
      type: string
      label: 'ETag identifier from Google Analytics Metadata API'
    metadata_last_time:
      type: string
      label: 'Lat time request for Google Analytics Metadata API'
